name: Cleanup Ephemeral Environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ needs.build.outputs.releaseTag }}
      NAMESPACE: ${{ github.ref == 'refs/heads/main' && 'prod' || needs.build.outputs.releaseTag }}
      TF_CLOUD_ORGANIZATION: "mshade"
      TF_WORKSPACE: "taskly"
      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
      CONFIG_DIRECTORY: "./deploy/tf"
      KUBECONFIG: "/tmp/taskly-kubeconfig.yaml"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Get Kubeconfig from TF state
        working-directory: deploy/tf
        run: |
          terraform init
          terraform output taskly_kubeconfig | base64 -d > ${{ env.KUBECONFIG }}
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy Taskly to k8s
        working-directory: deploy
        run: |
          kubectl delete ns ${{ env.NAMESPACE }}
